name: Publish Package to npmjs
on:
    push:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
            - run: yarn --frozen-lockfile
            - name: Clean npm cache
              run: |
                  rm -rf node_modules
                  rm -f package-lock.json
            - name: NPM Install
              run: npm install
            - name: Npm run CI
              run: npm run ci

    publish-npm:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
                  registry-url: https://registry.npmjs.org/
            - name: Clean npm cache
              run: |
                  rm -rf node_modules
                  rm -f package-lock.json
            - name: NPM Install
              run: npm install
            - name: Npm run build
              run: npm run build
            - run: npm publish
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
